[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/public/index.html"
  status = 200

[[redirects]]
  from = "/weekly"
  to = "/private/recommendations.html"
  status = 200

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "no-store, max-age=0"
